name: test wabe-mongo-kvstorage
on: [push]
jobs:
  test-wabe-mongo-kvstorage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: '.docker-compose.test.yml'
          service: wabe-mongo-kvstorage
